# -*- mode: ruby -*-
# vi: set ft=ruby :

# 
# Settings related to creating an Active Directory Domain
#
# HOSTNAME - Hostname of the deployed VM
# DOMAIN - The AD domain DNS name that will be created
#

HOSTNAME = "dc01"
DOMAIN = "example.com"

#
# Settings related to creating a domain admin user
# 
# This allows creation of a user account that is automatically added to the domain admins and enterprise admins groups
#
# CREATE_DOMAIN_ADMIN - You can disable automatic creation of a domain admin user by setting this to false
# DOMAIN_ADMIN_GIVENNAME - The value assigned to attribute cde /
# DOMAIN_ADMIN_SN - The value assigned to attribute sn
# DOMAIN_ADMIN_USERNAME - This is the username that the domain admin will have. 
#                         Attributes sAMAccountName, userPrincipalName, displayName and email are also set using this value
# DOMAIN_ADMIN_PASSWORD - This is the password that the domain admin will have

CREATE_DOMAIN_ADMIN = true
DOMAIN_ADMIN_GIVENNAME = "yoda"
DOMAIN_ADMIN_SN = " "
DOMAIN_ADMIN_USERNAME = "yoda"
DOMAIN_ADMIN_PASSWORD = "UseTheF0rce"

#
# Settings related to creating ldap sync user.
# 
# The user account is created with the following attributes:
#     givenName:    alfresco
#     sn:           ldap
#     displayName:  alfresco ldap
# CREATE_LDAP_USER - You can disable automatic creation of a ldap sync user by setting this to false
# LDAP_USER_USERNAME -  This is the username that the ldap user will have. 
#                       Attributes sAMAccountName, userPrincipalName,  and email are also set using this value
# LDAP_USER_PASSWORD - This is the password that the ldap user will have

CREATE_LDAP_USER = true
LDAP_USER_USERNAME = "alfresco.ldap"
LDAP_USER_PASSWORD = "C0mplexPassword"

#
# Settings related to creating a keytab file
#
# CREATE_KEY_TAB - You can disbale automatic creation of a keytab by setting this to false.
# ACS_HOSTNAME -  This should be set to the hostname of the ACS server. 
#                 It ensures that the deligated Kerberos user and keytab file are 
#                 configured for requests from the correct server. Requires CREATE_KEY_TAB = true. 
# ACS_KEYTAB_PASSWORD - Password set for deligated Kerberos user and keytab.
#

CREATE_KEY_TAB = true
ACS_HOSTNAME = "acs1"
ACS_KEYTAB_PASSWORD = "ComplexPassw0rd"

#
# Private network switch ip address - This is optional 
#

PRIVATE_NETWORK_IP = "192.168.100.25"

#
# Box related parameters
#
# Change at your own risk. This has not been tested with any other boxes then the bellow 
#

VAGRANTFILE_API_VERSION = "2"
BASE_BOX = "gusztavvargadr/windows-server"
BASE_BOX_VERSION = "1607.0.2006.standard"
GUEST_OS = :windows

SSH_FORWARD_PORT = "52225"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  ## do not configure proxy 
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.enabled = false
  end

  config.vm.guest = GUEST_OS

  # See https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true


  # host port is incremented to allow vagrant.exe rdp command to work on Win 10
  config.vm.network "forwarded_port", guest: 3389, host: 3390, auto_correct: true

  # override default forwarded port for ssh
  config.vm.network :forwarded_port, guest: 22, host: SSH_FORWARD_PORT, id: "ssh"

  config.vm.network "private_network", ip: PRIVATE_NETWORK_IP

  config.vm.box = BASE_BOX
  config.vm.box_version = BASE_BOX_VERSION
  config.vm.define HOSTNAME
  config.vm.hostname = HOSTNAME
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--audio", "none"]
    v.customize ["modifyvm", :id, "--memory", 8192]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--name", HOSTNAME]
  end

  config.vm.provider :hyperv do |h|
    h.memory=4096
    h.cpus=2
    h.vmname=HOSTNAME
  end

  config.vm.provision "shell", path: "provision/setup-AD.ps1", args: [DOMAIN]
  config.vm.provision "shell", reboot: true
  config.vm.provision "shell", path: "provision/provision-users-and-groups.ps1"
  if CREATE_KEY_TAB
    config.vm.provision "shell", path: "provision/provision-kerberos-principle.ps1", args: [ACS_HOSTNAME, ACS_KEYTAB_PASSWORD]
  end

  if CREATE_LDAP_USER
    config.vm.provision "shell", path: "provision/provision-ldap-sync-user.ps1", args: [LDAP_USER_USERNAME, LDAP_USER_PASSWORD]
  end

  if CREATE_DOMAIN_ADMIN
    config.vm.provision "shell", path: "provision/provision-domain-admin.ps1", args: [DOMAIN_ADMIN_GIVENNAME, DOMAIN_ADMIN_SN, DOMAIN_ADMIN_USERNAME, DOMAIN_ADMIN_PASSWORD]
  end
end
